global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'identity-api'
    static_configs:
      - targets: ['identity-api:9090']
  - job_name: 'properties-api'
    static_configs:
      - targets: ['properties-api:9090']
  - job_name: 'sensors-api'
    static_configs:
      - targets: ['sensors-api:9090']
  - job_name: 'alerts-api'
    static_configs:
      - targets: ['alerts-api:9090']
